### ISSUE TITLE
Custom Snippet Breakage

### ISSUE THREAD

**Issue by chriscoyier** [emmetio/codemirror-plugin#11]
A user of CodePen found that if you make a custom snippet that is essentially:

```
"gt": "grid-template: repeat(2,auto) / repeat(auto-fit, minmax(250px, 1fr))"
```

Emmet 2 doesn't expand that but instead moves focus out of the editor.

**Comment by jsnkuhn** [comment]
I am the above mentioned codepen user.
 
After having deleted the above custom snippet Emmet expansion now generally works (i.e. the short cuts compute to something) but anything with multiple tab stops, either custom or default, doesn't behave as expected.

`tsh` computes to only `text-shadow: hoff   ;` instead of the expected `text-shadow: hoff voff blur #000;` and pressing tab, tabs the whole line to the right instead of jumping to the next stop??? This seems to happen whether i'm logged in or not so appears not related to the custom snippet breaking. But...

Also have a new custom snippet for "size" that should output width and height with 2 tab stops that breaks similarly, animated gif is attached. Snippet code is:

```width: ${1:200}px;\nheight: ${2:200}px;```

![size-snippet](https://user-images.githubusercontent.com/1286791/90272141-8c296980-de22-11ea-86fb-6ee1d76b3318.gif)

**Comment by sergeche** [comment]
> tsh computes to only text-shadow: hoff ; instead of the expected text-shadow: hoff voff blur #000;

Will be fixed in next release.

> and pressing tab, tabs the whole line to the right instead of jumping to the next stop???

CodeMirror doesn’t support tabstops like in VSCode or Sublime Text. It may require additional (not yet written?) plugin.

> Also have a new custom snippet for "size" that should output width and height with 2 tab stops that breaks similarly

This is how CodeMirror works if you have something selected and press Tab, not Emmet

**Comment by sergeche** [comment]
Allow slash in CSS values in v1.2.3
